### ISSUE TITLE
Wrong time returned when using `{ long: true }`

### ISSUE THREAD

**Issue by BrandonZacharie** [zeit/ms#105]
Consider the following
```javascript
> t = 21600001
21600001
> ms(t)
'6h'
> ms(t, { long: true })
'7 hours'
```
and note that `ms` returned a different time value with `{ long: true }` options
```javascript
> h = t / 1000 / 60 / 60 // hours
6.000000277777778
> Math.ceil(h)
7
```
which is the result if something like `Math.ceil` were used in the conversion.

## tl;dr
When given a number that cannot be divided evenly in to a unit of time (e.g. `21600001` ) and `{ long: true }`, `ms` returns the wrong time.

Where `n = 21600001 / 1000 / 60 / 60`
expected: `${n} hours`
actual:  `${n + 1} hours`

**EDIT**:
I'm using version 2.0.0

**Comment by yoavmmn** [comment]
I can't reproduce your issue. you must be using an old version.

**Comment by leo** [comment]
@BrandonZacharie Which versions are you using?

**Comment by BrandonZacharie** [comment]
I have ms@2.0.0 via several dependencies in my project.

**Comment by yoavmmn** [comment]
@BrandonZacharie Use the latest version. In version 2.1.1 we switched from `Math.ceil` to `Math.round` thanks to @thevtm.
