### ISSUE TITLE
"1 week" returns undefined

### ISSUE THREAD

**Issue by okor** [zeit/ms#46]
I would expect "1 week" to return a result.

```
> ~/Projects/voxmedia/tempo $ npm install ms
ms@0.7.0 node_modules/ms
~/Projects/voxmedia/tempo $ node
> var ms = require('ms')
undefined
> ms('5 minutes')
300000
> ms('15 minutes')
900000
> ms('2 hours')
7200000
> ms('2 hour')
7200000
> ms('2 h')
7200000
> ms('1 day')
86400000
> ms('1 week')
undefined
> ms('1 weeks')
undefined
> ms('1 month')
undefined
> ms('1 year')
31557600000
```

I would also expect "1 month" to return a result (though that one is slightly tricky) and sources seem to disagree. 

![month](https://cloud.githubusercontent.com/assets/142910/7054100/4aa2628e-de08-11e4-8944-ee7070e6def2.png)

^ I would probably just call it 30 days even and be done with it. Maybe include a note in the docs as to what the library considers 1 month.

Anyhow, weeks should probably work. Otherwise the lib is great. Thanks!

**Comment by okor** [comment]
And perhaps it would be appropriate to throw an Error if no result can be returned.

**Comment by havenchyk** [comment]
@okor If the problem still exists, PR is welcomed!

**Comment by LinusU** [comment]
I would recommend throwing an error, that is what I'm doing in [parse-iso-duration](https://github.com/LinusU/node-parse-iso-duration).

```javascript
throw new Error('Ambiguous duration')
```

**Comment by yvele** [comment]
The month unit is discussed in a dedicated issue: https://github.com/rauchg/ms.js/issues/57

**Comment by leo** [comment]
https://github.com/zeit/ms/issues/57
