### ISSUE TITLE
NPM BREAKING BUG => `ms` module breaks build

### ISSUE THREAD

**Issue by meticulo3366** [zeit/ms#56]
Version `0.7.1` Is breaking NPM builds, due to some bad characters, package.json is below

![screen shot 2015-11-18 at 4 36 43 pm](https://cloud.githubusercontent.com/assets/3074572/11255251/1ca98464-8e13-11e5-889e-3e53ecfa45f6.png)

![screen shot 2015-11-18 at 4 37 30 pm](https://cloud.githubusercontent.com/assets/3074572/11255252/1cb36042-8e13-11e5-8c8d-85e76ef55543.png)

{
  "name": "ms",
  "version": "0.7.1",
  "description": "Tiny ms conversion utility",
  "repository": {
    "type": "git",
    "url": "git://github.com/guille/ms.js.git"
  },
  "main": "./index",
  "devDependencies": {
    "mocha": "*",
    "expect.js": "*",
    "serve": "*"
  },
  "component": {
    "scripts": {
      "ms/index.js": "index.js"
    }
  },
  "gitHead": "713dcf26d9e6fd9dbc95affe7eff9783b7f1b909",
  "bugs": {
    "url": "https://github.com/guille/ms.js/issues"
  },
  "homepage": "https://github.com/guille/ms.js",
  "_id": "ms@0.7.1",
  "scripts": {},
  "_shasum": "9cd13c03adbff25b65effde7ce864ee952017098",
  "_from": "ms@0.7.1",
  "_npmVersion": "2.7.5",
  "_nodeVersion": "0.12.2",
  "_npmUser": {
    "name": "rauchg",
    "email": "rauchg@gmail.com"
  },
  "maintainers": [
    {
      "name": "rauchg",
      "email": "rauchg@gmail.com"
    }
  ],
  "dist": {
    "shasum": "9cd13c03adbff25b65effde7ce864ee952017098",
    "tarball": "http://registry.npmjs.org/ms/-/ms-0.7.1.tgz"
  },
  "directories": {},
  "_resolved": "https://registry.npmjs.org/ms/-/ms-0.7.1.tgz"
}

**Comment by leo** [comment]
The content of your editor doesn't look right at all. What's with all of these `NUL`s?
